INSERT INTO TEAMS VALUES (1,'LOS VENGADORES');
INSERT INTO TEAMS VALUES (2,'LA LIGA DE LA JUSTICIA');
INSERT INTO SUPERHEROS VALUES (1, 'SUPERMAN', 'Volar y superfuerza',2);
INSERT INTO SUPERHEROS VALUES (2, 'SPIDERMAN', 'Poderes de araña',1);
INSERT INTO SUPERHEROS VALUES (3, 'THOR', 'Dios del trueno',1);
INSERT INTO SUPERHEROS VALUES (4, 'FLASH', 'Supervelocidad',2);